### ISSUE TITLE
Consider abstracting paths from deployment.yml

### ISSUE THREAD

**Issue by kyleabenson** [rhmk/ansible-hana-examples#30]
Currently there is a lot of hardcoding of paths in deployment > tasks > deployment.yml, for example:

```
- name: create usr sap directory
  file:
    path: "/usr/sap/{{ item.value.hana_sid|upper }}"
    state: directory
  with_dict: "{{ instances }}"
```
I count that path 3 times in that file, so we could do something like:

```
var: 
  sap_usr_path: /usr/sap/{{ item.value.hana_sid|upper }}
```

This would improve legibility and reduce the number of manual paths, so it becomes easier to modify in the future if necessary. This is generally a good practice from a role reuse perspective.
